from enum import StrEnum


class ArtifactType(StrEnum):
    VISION_DOC = "VISION_DOC"
    DESIGN_PILLARS = "DESIGN_PILLARS"
    MECHANICS_SPEC = "MECHANICS_SPEC"
    SYSTEMS_SPEC = "SYSTEMS_SPEC"
    NARRATIVE_SPEC = "NARRATIVE_SPEC"
    EXPERIENCE_MILESTONES = "EXPERIENCE_MILESTONES"
    ART_DIRECTION = "ART_DIRECTION"
    ASSET_LIST = "ASSET_LIST"
    ASSET_PROMPTS = "ASSET_PROMPTS"
    GAME_BUNDLE = "GAME_BUNDLE"
    QA_ISSUES = "QA_ISSUES"
    COHERENCE_REVIEW = "COHERENCE_REVIEW"
    PRODUCER_NOTES = "PRODUCER_NOTES"
    REFLECTION_NOTE = "REFLECTION_NOTE"
    BINARY_ASSET = "BINARY_ASSET"
