from enum import StrEnum


class ProjectStatus(StrEnum):
    PENDING = "PENDING"
    VISION_IN_PROGRESS = "VISION_IN_PROGRESS"
    VISION_DONE = "VISION_DONE"
    DESIGN_IN_PROGRESS = "DESIGN_IN_PROGRESS"
    DESIGN_DONE = "DESIGN_DONE"
    STORY_IN_PROGRESS = "STORY_IN_PROGRESS"
    STORY_DONE = "STORY_DONE"
    ART_IN_PROGRESS = "ART_IN_PROGRESS"
    ART_DONE = "ART_DONE"
    ENGINEERING_IN_PROGRESS = "ENGINEERING_IN_PROGRESS"
    ENGINEERING_DONE = "ENGINEERING_DONE"
    QA_IN_PROGRESS = "QA_IN_PROGRESS"
    QA_DONE = "QA_DONE"
    PRODUCER_IN_PROGRESS = "PRODUCER_IN_PROGRESS"
    PRODUCER_DONE = "PRODUCER_DONE"
    DONE = "DONE"
    FAILED = "FAILED"
