"""Compile a Phaser 3 entry script from structured GameBundle IR."""

from __future__ import annotations

from gamebuilder.team.engineering.domain.model import (
    CollectibleSpec,
    GameBundle,
    HazardSpec,
    PlatformSpec,
)

_PHYSICS = {
    "snappy": {"gravity": 1100, "move": 200, "jump": -380},
    "floaty": {"gravity": 650, "move": 170, "jump": -300},
    "heavy": {"gravity": 1400, "move": 150, "jump": -320},
}


def compile_phaser_entry(
    *,
    title: str,
    background_hex: str,
    player_hex: str,
    platform_hex: str,
    goal_hex: str,
    player_start_x: int,
    player_start_y: int,
    platforms: list[PlatformSpec],
    goal: PlatformSpec,
    hazards: list[HazardSpec] | None = None,
    collectibles: list[CollectibleSpec] | None = None,
    world_width: int = 800,
    world_height: int = 450,
    physics_profile: str = "snappy",
    hero_texture_url: str = "",
    backdrop_texture_url: str = "",
    hazard_texture_url: str = "",
    platform_texture_url: str = "",
    collectible_texture_url: str = "",
    hero_display_w: int = 28,
    hero_display_h: int = 32,
    hazard_display_w: int = 32,
    hazard_display_h: int = 32,
    collectible_display_w: int = 20,
    collectible_display_h: int = 20,
) -> str:
    """Return a self-contained Phaser scene that mounts on #game-root."""
    hazards = hazards or []
    collectibles = collectibles or []
    physics = _PHYSICS.get(physics_profile, _PHYSICS["snappy"])
    platform_rows = ",\n".join(
        f"      {{ x: {p.x}, y: {p.y}, w: {p.w}, h: {p.h} }}" for p in platforms
    )
    hazard_rows = ",\n".join(
        f"      {{ x: {h.x}, y: {h.y}, w: {h.w}, h: {h.h} }}" for h in hazards
    )
    collectible_rows = ",\n".join(
        f"      {{ x: {c.x}, y: {c.y}, w: {c.w}, h: {c.h} }}" for c in collectibles
    )
    safe_title = title.replace("\\", "\\\\").replace("'", "\\'")
    hero_url = _js_string(hero_texture_url)
    backdrop_url = _js_string(backdrop_texture_url)
    hazard_url = _js_string(hazard_texture_url)
    platform_url = _js_string(platform_texture_url)
    collectible_url = _js_string(collectible_texture_url)
    need_collect_all = "true" if collectibles else "false"
    return f"""/* Generated by Cyborg Studios Engineering IR compiler — {safe_title} */
(function () {{
  const root = document.getElementById('game-root');
  if (!root || typeof Phaser === 'undefined') {{
    console.error('Phaser or #game-root missing');
    return;
  }}

  const WIDTH = {int(world_width)};
  const HEIGHT = {int(world_height)};
  const VIEW_W = Math.min(800, WIDTH);
  const VIEW_H = Math.min(450, HEIGHT);
  const MOVE = {physics["move"]};
  const JUMP = {physics["jump"]};
  const GRAVITY = {physics["gravity"]};
  const NEED_COLLECT_ALL = {need_collect_all};
  const HERO_W = {int(hero_display_w)};
  const HERO_H = {int(hero_display_h)};
  const HAZARD_W = {int(hazard_display_w)};
  const HAZARD_H = {int(hazard_display_h)};
  const GEM_W = {int(collectible_display_w)};
  const GEM_H = {int(collectible_display_h)};
  const platforms = [
{platform_rows}
  ];
  const hazards = [
{hazard_rows}
  ];
  const collectibles = [
{collectible_rows}
  ];
  const goal = {{ x: {goal.x}, y: {goal.y}, w: {goal.w}, h: {goal.h} }};
  const SPAWN = {{ x: {player_start_x}, y: {player_start_y} }};
  const TEXTURES = {{
    hero: {hero_url},
    backdrop: {backdrop_url},
    hazard: {hazard_url},
    platform: {platform_url},
    collectible: {collectible_url},
  }};

  class MainScene extends Phaser.Scene {{
    constructor() {{
      super('main');
      this.won = false;
      this.collected = 0;
      this.collectibleTotal = collectibles.length;
    }}

    preload() {{
      if (TEXTURES.hero) this.load.image('hero', TEXTURES.hero);
      if (TEXTURES.backdrop) this.load.image('backdrop', TEXTURES.backdrop);
      if (TEXTURES.hazard) this.load.image('hazard', TEXTURES.hazard);
      if (TEXTURES.platform) this.load.image('platform', TEXTURES.platform);
      if (TEXTURES.collectible) this.load.image('collectible', TEXTURES.collectible);
    }}

    create() {{
      this.cameras.main.setBackgroundColor('{background_hex}');
      this.cameras.main.setBounds(0, 0, WIDTH, HEIGHT);
      this.physics.world.setBounds(0, 0, WIDTH, HEIGHT);

      if (this.textures.exists('backdrop')) {{
        this.add.image(WIDTH / 2, HEIGHT / 2, 'backdrop').setDisplaySize(WIDTH, HEIGHT).setDepth(-10);
      }}

      this.add
        .text(16, 12, '{safe_title}', {{
          fontFamily: 'monospace',
          fontSize: '14px',
          color: '{player_hex}',
        }})
        .setScrollFactor(0)
        .setDepth(20);

      this.statusText = this.add
        .text(16, 32, '', {{
          fontFamily: 'monospace',
          fontSize: '12px',
          color: '{goal_hex}',
        }})
        .setScrollFactor(0)
        .setDepth(20);
      this._refreshStatus();

      const solids = this.physics.add.staticGroup();
      platforms.forEach((p) => {{
        let block;
        if (this.textures.exists('platform')) {{
          block = this.add.tileSprite(p.x, p.y, p.w, p.h, 'platform');
        }} else {{
          block = this.add.rectangle(
            p.x,
            p.y,
            p.w,
            p.h,
            Phaser.Display.Color.HexStringToColor('{platform_hex}').color
          );
        }}
        this.physics.add.existing(block, true);
        solids.add(block);
      }});

      const hazardGroup = this.physics.add.staticGroup();
      hazards.forEach((h) => {{
        let body;
        if (this.textures.exists('hazard')) {{
          body = this.add.image(h.x, h.y, 'hazard').setDisplaySize(h.w || HAZARD_W, h.h || HAZARD_H);
        }} else {{
          body = this.add.rectangle(h.x, h.y, h.w || HAZARD_W, h.h || HAZARD_H, 0xc45c26);
        }}
        this.physics.add.existing(body, true);
        hazardGroup.add(body);
      }});

      this.collectibleGroup = this.physics.add.staticGroup();
      collectibles.forEach((c) => {{
        let gem;
        if (this.textures.exists('collectible')) {{
          gem = this.add.image(c.x, c.y, 'collectible').setDisplaySize(c.w || GEM_W, c.h || GEM_H);
        }} else {{
          gem = this.add.rectangle(
            c.x,
            c.y,
            c.w || GEM_W,
            c.h || GEM_H,
            Phaser.Display.Color.HexStringToColor('{goal_hex}').color
          );
        }}
        this.physics.add.existing(gem, true);
        this.collectibleGroup.add(gem);
      }});

      const goalRect = this.add.rectangle(
        goal.x,
        goal.y,
        goal.w,
        goal.h,
        Phaser.Display.Color.HexStringToColor('{goal_hex}').color
      );
      this.physics.add.existing(goalRect, true);
      this.goalBody = goalRect;

      if (this.textures.exists('hero')) {{
        this.player = this.physics.add.image(SPAWN.x, SPAWN.y, 'hero');
        this.player.setDisplaySize(HERO_W, HERO_H);
        this.player.body.setSize(HERO_W * 0.7, HERO_H * 0.85);
      }} else {{
        this.player = this.add.rectangle(
          SPAWN.x,
          SPAWN.y,
          Math.max(20, HERO_W - 4),
          Math.max(24, HERO_H - 4),
          Phaser.Display.Color.HexStringToColor('{player_hex}').color
        );
        this.physics.add.existing(this.player);
      }}
      this.player.body.setCollideWorldBounds(true);
      this.player.body.setBounce(0.02);
      this.cameras.main.startFollow(this.player, true, 0.12, 0.12);

      this.physics.add.collider(this.player, solids);
      this.physics.add.overlap(this.player, hazardGroup, () => this._fail(), null, this);
      this.physics.add.overlap(this.player, this.collectibleGroup, (_p, gem) => this._collect(gem), null, this);
      this.physics.add.overlap(this.player, this.goalBody, () => this._tryWin(), null, this);

      this.cursors = this.input.keyboard.createCursorKeys();
      this.wasd = this.input.keyboard.addKeys('W,A,S,D,SPACE');
      this.banner = this.add
        .text(VIEW_W / 2, VIEW_H / 2, '', {{
          fontFamily: 'monospace',
          fontSize: '22px',
          color: '{goal_hex}',
        }})
        .setOrigin(0.5)
        .setScrollFactor(0)
        .setDepth(30);

      if (window.parent && window.parent !== window) {{
        window.parent.postMessage({{ type: 'cyborg-play-ready', runtime: 'ir' }}, '*');
      }}
    }}

    _refreshStatus() {{
      if (!this.statusText) return;
      if (this.collectibleTotal > 0) {{
        this.statusText.setText('Gems ' + this.collected + '/' + this.collectibleTotal);
      }} else {{
        this.statusText.setText('Reach the goal · avoid hazards');
      }}
    }}

    _collect(gem) {{
      if (!gem.active) return;
      gem.destroy();
      this.collected += 1;
      this._refreshStatus();
    }}

    _fail() {{
      if (this.won) return;
      this.player.body.reset(SPAWN.x, SPAWN.y);
      this.banner.setText('OUCH');
      this.time.delayedCall(500, () => {{ if (!this.won) this.banner.setText(''); }});
    }}

    _tryWin() {{
      if (this.won) return;
      if (NEED_COLLECT_ALL && this.collected < this.collectibleTotal) {{
        this.banner.setText('NEED GEMS');
        this.time.delayedCall(600, () => {{ if (!this.won) this.banner.setText(''); }});
        return;
      }}
      this.won = true;
      this.banner.setText('CLEAR');
      this.player.body.setVelocity(0, 0);
      if (window.parent && window.parent !== window) {{
        window.parent.postMessage({{ type: 'cyborg-play-clear', runtime: 'ir' }}, '*');
      }}
    }}

    update() {{
      if (this.won || !this.player) return;
      const body = this.player.body;
      const left = this.cursors.left.isDown || this.wasd.A.isDown;
      const right = this.cursors.right.isDown || this.wasd.D.isDown;
      const jump =
        this.cursors.up.isDown ||
        this.cursors.space.isDown ||
        this.wasd.W.isDown ||
        this.wasd.SPACE.isDown;
      body.setVelocityX(0);
      if (left) body.setVelocityX(-MOVE);
      if (right) body.setVelocityX(MOVE);
      if (jump && body.blocked.down) body.setVelocityY(JUMP);
      if (this.player.y > HEIGHT + 80) this._fail();
    }}
  }}

  if (window.__cyborgGame) {{
    try {{ window.__cyborgGame.destroy(true); }} catch (e) {{}}
  }}
  window.__cyborgGame = new Phaser.Game({{
    type: Phaser.AUTO,
    parent: 'game-root',
    width: VIEW_W,
    height: VIEW_H,
    backgroundColor: '{background_hex}',
    physics: {{
      default: 'arcade',
      arcade: {{ gravity: {{ y: GRAVITY }}, debug: false }},
    }},
    scene: [MainScene],
    scale: {{ mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }},
  }});
}})();
"""


def _js_string(value: str) -> str:
    if not value:
        return "''"
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\n", "\\n")
    )
    return f"'{escaped}'"


def with_compiled_entry(bundle: GameBundle) -> GameBundle:
    source = compile_phaser_entry(
        title=bundle.title,
        background_hex=bundle.background_hex,
        player_hex=bundle.player_hex,
        platform_hex=bundle.platform_hex,
        goal_hex=bundle.goal_hex,
        player_start_x=bundle.player_start_x,
        player_start_y=bundle.player_start_y,
        platforms=bundle.platforms,
        goal=bundle.goal,
        hazards=bundle.hazards,
        collectibles=bundle.collectibles,
        world_width=bundle.world_width,
        world_height=bundle.world_height,
        physics_profile=bundle.physics_profile,
        hero_texture_url=bundle.hero_texture_url,
        backdrop_texture_url=bundle.backdrop_texture_url,
        hazard_texture_url=bundle.hazard_texture_url,
        platform_texture_url=bundle.platform_texture_url,
        collectible_texture_url=bundle.collectible_texture_url,
        hero_display_w=bundle.hero_display_w,
        hero_display_h=bundle.hero_display_h,
        hazard_display_w=bundle.hazard_display_w,
        hazard_display_h=bundle.hazard_display_h,
        collectible_display_w=bundle.collectible_display_w,
        collectible_display_h=bundle.collectible_display_h,
    )
    return bundle.model_copy(update={"entry_source": source})
