"""Compile a Phaser 3 entry script from a structured GameBundle (no entrySource)."""

from gamebuilder.team.engineering.domain.model import GameBundle, PlatformSpec


def compile_phaser_entry(
    *,
    title: str,
    background_hex: str,
    player_hex: str,
    platform_hex: str,
    goal_hex: str,
    player_start_x: int,
    player_start_y: int,
    platforms: list[PlatformSpec],
    goal: PlatformSpec,
) -> str:
    """Return a self-contained Phaser scene that mounts on #game-root."""
    platform_rows = ",\n".join(
        f"      {{ x: {p.x}, y: {p.y}, w: {p.w}, h: {p.h} }}" for p in platforms
    )
    safe_title = title.replace("\\", "\\\\").replace("'", "\\'")
    return f"""/* Generated by Cyborg Studios Engineering — {safe_title} */
(function () {{
  const root = document.getElementById('game-root');
  if (!root || typeof Phaser === 'undefined') {{
    console.error('Phaser or #game-root missing');
    return;
  }}

  const WIDTH = 800;
  const HEIGHT = 450;
  const platforms = [
{platform_rows}
  ];
  const goal = {{ x: {goal.x}, y: {goal.y}, w: {goal.w}, h: {goal.h} }};

  class MainScene extends Phaser.Scene {{
    constructor() {{
      super('main');
      this.player = null;
      this.cursors = null;
      this.wasd = null;
      this.won = false;
    }}

    create() {{
      this.cameras.main.setBackgroundColor('{background_hex}');
      this.add
        .text(16, 12, '{safe_title}', {{
          fontFamily: 'monospace',
          fontSize: '14px',
          color: '{player_hex}',
        }})
        .setScrollFactor(0);

      const solids = this.physics.add.staticGroup();
      for (const p of platforms) {{
        const block = this.add.rectangle(p.x, p.y, p.w, p.h, Phaser.Display.Color.HexStringToColor('{platform_hex}').color);
        this.physics.add.existing(block, true);
        solids.add(block);
      }}

      const goalRect = this.add.rectangle(
        goal.x,
        goal.y,
        goal.w,
        goal.h,
        Phaser.Display.Color.HexStringToColor('{goal_hex}').color
      );
      this.physics.add.existing(goalRect, true);
      this.goalBody = goalRect;

      this.player = this.add.rectangle(
        {player_start_x},
        {player_start_y},
        24,
        28,
        Phaser.Display.Color.HexStringToColor('{player_hex}').color
      );
      this.physics.add.existing(this.player);
      this.player.body.setCollideWorldBounds(true);
      this.player.body.setBounce(0.05);

      this.physics.add.collider(this.player, solids);
      this.physics.add.overlap(this.player, this.goalBody, () => this._win(), null, this);

      this.cursors = this.input.keyboard.createCursorKeys();
      this.wasd = this.input.keyboard.addKeys('W,A,S,D,SPACE');
      this.winText = this.add
        .text(WIDTH / 2, HEIGHT / 2, '', {{
          fontFamily: 'monospace',
          fontSize: '22px',
          color: '{goal_hex}',
        }})
        .setOrigin(0.5)
        .setScrollFactor(0);
    }}

    _win() {{
      if (this.won) return;
      this.won = true;
      this.winText.setText('CLEAR');
      this.player.body.setVelocity(0, 0);
    }}

    update() {{
      if (this.won || !this.player) return;
      const body = this.player.body;
      const left = this.cursors.left.isDown || this.wasd.A.isDown;
      const right = this.cursors.right.isDown || this.wasd.D.isDown;
      const jump =
        this.cursors.up.isDown ||
        this.cursors.space.isDown ||
        this.wasd.W.isDown ||
        this.wasd.SPACE.isDown;

      body.setVelocityX(0);
      if (left) body.setVelocityX(-180);
      if (right) body.setVelocityX(180);
      if (jump && body.blocked.down) body.setVelocityY(-320);
    }}
  }}

  if (window.__cyborgGame) {{
    window.__cyborgGame.destroy(true);
    window.__cyborgGame = null;
  }}

  window.__cyborgGame = new Phaser.Game({{
    type: Phaser.AUTO,
    parent: 'game-root',
    width: WIDTH,
    height: HEIGHT,
    backgroundColor: '{background_hex}',
    physics: {{
      default: 'arcade',
      arcade: {{ gravity: {{ y: 900 }}, debug: false }},
    }},
    scene: [MainScene],
    scale: {{ mode: Phaser.Scale.FIT, autoCenter: Phaser.Scale.CENTER_BOTH }},
  }});
}})();
"""


def with_compiled_entry(bundle: GameBundle) -> GameBundle:
    source = compile_phaser_entry(
        title=bundle.title,
        background_hex=bundle.background_hex,
        player_hex=bundle.player_hex,
        platform_hex=bundle.platform_hex,
        goal_hex=bundle.goal_hex,
        player_start_x=bundle.player_start_x,
        player_start_y=bundle.player_start_y,
        platforms=bundle.platforms,
        goal=bundle.goal,
    )
    return bundle.model_copy(update={"entry_source": source})
